### ISSUE TITLE
Drop TODO list in readme.md in favor of issues

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo_batc#3]
Drop TODO list in readme.md -> use https://github.com/roboticslab-uc3m/teo_batc/issues/new
:smiley: :smiley: :smiley: 
:smiley: :cat: :smiley: 
:smiley: :smiley: :smiley:

**Comment by David-Estevez** [comment]
:+1: :+1: :+1: 
:+1: :smile_cat: :+1: 
:+1: :+1: :+1:
